ENV["LC_ALL"] = "en_US.UTF-8"



Vagrant.configure("2") do |config|
  ## Disable auto update of VirtualBox Guest Additions
  config.vbguest.auto_update = false

  ## NameServer 1
  config.vm.define "ns1" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"   

    subconfig.vm.hostname = "ns1"

    # Set up networks
    subconfig.vm.network "private_network",

      ip: "192.168.1.2", 

      virtualbox__intnet: "intnet1"

    subconfig.vm.provider "virtualbox" do |vb|

      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/B3"]

      vb.customize ["modifyvm", :id, "--memory", "1024"]

      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end

    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL

      echo "192.168.1.3 ns2" | sudo tee -a /etc/hosts

      echo "192.168.1.4 ns3" | sudo tee -a /etc/hosts

      echo "192.168.1.5 client" | sudo tee -a /etc/hosts

      sudo apt update

      sudo apt install -y net-tools traceroute bind9
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/ns1.sh"
  end

  ## NameServer 2
  config.vm.define "ns2" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"

    subconfig.vm.hostname = "ns2"
    
    # Set up networks
    subconfig.vm.network "private_network",

      ip: "192.168.1.3", 

      virtualbox__intnet: "intnet1"
    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/B3"]

      vb.customize ["modifyvm", :id, "--memory", "1024"]

      vb.customize ["modifyvm", :id, "--cpus", "2"]

    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL

      echo "192.168.1.2 ns1" | sudo tee -a /etc/hosts

      echo "192.168.1.4 ns3" | sudo tee -a /etc/hosts

      echo "192.168.1.5 client" | sudo tee -a /etc/hosts

      sudo apt update

      sudo apt install -y net-tools bind9

    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/ns2.sh"
  end

  ## NameServer 3
  config.vm.define "ns3" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"

    subconfig.vm.hostname = "ns3"

    # Set up networks
    subconfig.vm.network "private_network",

      ip: "192.168.1.4",

      virtualbox__intnet: "intnet1"

    subconfig.vm.provider "virtualbox" do |vb|

      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/B3"]

      vb.customize ["modifyvm", :id, "--memory", "1024"]

      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      echo "192.168.1.2 ns1" | sudo tee -a /etc/hosts

      echo "192.168.1.3 ns2" | sudo tee -a /etc/hosts

      echo "192.168.1.5 client" | sudo tee -a /etc/hosts

      sudo apt update

      sudo apt install -y net-tools bind9
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/ns3.sh"
  end

  ## Client
  config.vm.define "client" do |subconfig|
    # Set box and hostname
    subconfig.vm.box = "ubuntu/jammy64"

    subconfig.vm.hostname = "client"
    # Set up networks
    subconfig.vm.network "private_network",

      ip: "192.168.1.5",

      virtualbox__intnet: "intnet1"

    subconfig.vm.provider "virtualbox" do |vb|
      # Custom VM Group, memory, and CPU cores
      vb.customize ["modifyvm", :id, "--groups", "/B3"]

      vb.customize ["modifyvm", :id, "--memory", "1024"]

      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    # Add provisioning scripts
    subconfig.vm.provision "shell", inline: <<-SHELL
      echo "192.168.1.2 ns1" | sudo tee -a /etc/hosts

      echo "192.168.1.3 ns2" | sudo tee -a /etc/hosts

      echo "192.168.1.4 ns3" | sudo tee -a /etc/hosts

      sudo apt update

      sudo apt install -y net-tools bind9
    SHELL
    subconfig.vm.provision :shell, privileged: false, path: "scripts/client.sh"
  end
end