#Define Vagrant provider and vagrant Box. Number 2 in configure indicates configuration version. Check vagrant documentation for more details

ENV["LC_ALL"] = "en_US.UTF-8"


Vagrant.configure("2") do |config|    
  
    ## Disable auto update of VirtualBox Guest Addition
    config.vbguest.auto_update = false

    # Lab1
    config.vm.define "lab1" do |subconfig|

                  subconfig.vm.box = "ubuntu/jammy64"

                  subconfig.vm.hostname="lab1"

                  subconfig.vm.network "private_network", ip: "192.168.0.2",virtualbox__intnet: true,virtualbox__intnet:"intnet1"

                  subconfig.vm.network "private_network",ip: "192.168.2.2",virtualbox__intnet: true,virtualbox__intnet:"intnet2"

                  subconfig.vm.provider :virtualbox do |vb|

                                         # Custom CPU & Memory
                                          vb.customize ["modifyvm", :id, "--groups", "/B5"]

                                          vb.customize ["modifyvm", :id, "--memory", "4096"]

                                          vb.customize ["modifyvm", :id, "--cpus", "2"]

                                           # enable promiscuous mode on the network

                                          vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
                              
                                          vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]

                  end

                  #add provisioning scripts to Vagrantfile

                  subconfig.vm.provision "shell", inline: <<-SHELL

                            sudo echo "192.168.0.3 lab2" | sudo tee -a /etc/hosts

                            sudo echo "192.168.2.3 lab3" | sudo tee -a /etc/hosts

                            sudo apt update

                            sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils

                            

                  SHELL

                  subconfig.vm.provision :shell, privileged: false, path: "scripts/lab1.sh"


    end

    # Lab2
    config.vm.define "lab2" do |subconfig|

      subconfig.vm.box = "ubuntu/jammy64"

      subconfig.vm.hostname="lab2"

      subconfig.vm.network "private_network", ip: "192.168.0.3",virtualbox__intnet: true,virtualbox__intnet:"intnet1"


      subconfig.vm.provider :virtualbox do |vb|

                            # Custom CPU & Memory
                             vb.customize ["modifyvm", :id, "--groups", "/B5"]

                             vb.customize ["modifyvm", :id, "--memory", "4096"]

                             vb.customize ["modifyvm", :id, "--cpus", "2"]

                             
                            # enable promiscuous mode on the network

                            vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]

      end
    

      # Add provisioning scripts

      subconfig.vm.provision "shell", inline: <<-SHELL

          sudo echo "192.168.0.2 lab1" | sudo tee -a /etc/hosts

          sudo echo "192.168.2.3 lab3" | sudo tee -a /etc/hosts
          
          sudo apt update

          sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils

        SHELL

      subconfig.vm.provision :shell, privileged: false, path: "scripts/lab2.sh"

    end


    # Lab3
    config.vm.define "lab3" do |subconfig|

      subconfig.vm.box = "ubuntu/jammy64"

      subconfig.vm.hostname="lab3"

      subconfig.vm.network "private_network", ip: "192.168.2.3",virtualbox__intnet: true,virtualbox__intnet:"intnet2"


      subconfig.vm.provider :virtualbox do |vb|

                            # Custom CPU & Memory
                             vb.customize ["modifyvm", :id, "--groups", "/B5"]

                             vb.customize ["modifyvm", :id, "--memory", "4096"]

                             vb.customize ["modifyvm", :id, "--cpus", "2"]

                              # enable promiscuous mode on the network

                              vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]

      end
    

      # Add provisioning scripts

      subconfig.vm.provision "shell", inline: <<-SHELL


          sudo echo "192.168.2.2 lab1" | sudo tee -a /etc/hosts

          sudo echo "192.168.0.3 lab2" | sudo tee -a /etc/hosts

          sudo apt update

          sudo apt install -y net-tools inetutils-traceroute nmap openvpn bridge-utils

        SHELL

      subconfig.vm.provision :shell, privileged: false, path: "scripts/lab3.sh"

      end

end